apiVersion: v1
kind: Service
metadata:
  name: showcase
  labels:
    app: showcase
spec:
  selector:
    app: showcase
  ports:
    - name: http
      port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: showcase
  labels:
    version: v1
spec:
  replicas: #{replicas}#
  selector:
    matchLabels:
      app: showcase
  template:
    metadata:
      labels:
        app: showcase
        version: v1
    spec:
      containers:
        - name: showcase
          image: breadcrumbs.azurecr.io/showcase:#{Build.BuildId}#
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: #{cpu-limit}#
              memory: #{memory-limit}#
            requests:
              cpu: #{cpu}#
              memory: #{memory}#

